const defaults = {
  alignContent: {
    start: 'flex-start',
    end: 'flex-end',
    center: 'center',
    stretch: 'stretch',
    around: 'space-around',
    between: 'space-between',
  },
  alignItems: {
    start: 'flex-start',
    end: 'flex-end',
    center: 'center',
    baseline: 'baseline',
    stretch: 'stretch',
  },
  alignSelf: {
    start: 'flex-start',
    end: 'flex-end',
    center: 'center',
    baseline: 'baseline',
    stretch: 'stretch',
  },
  backgroundSizes: ['contain', 'cover'],
  baseColors: null,
  // borderCollapse: true,
  // borderPositions: true,
  borderRadii: {
    none: 'none',
    xs: '0.15em',
    sm: '0.3em',
    md: '0.6em',
    lg: '1em',
    xl: '1.8em',
    pill: '100em',
    '100': '100%',
  },
  borderRadiiPositions: ['left', 'top', 'right', 'bottom'],
  // borderRemoval: true,
  borderStyles: ['solid', 'dotted', 'dashed'],
  borderWidths: {
    xxs: '0.05rem',
    sm: '0.15rem',
    md: '0.3rem',
    lg: '0.6rem',
    xl: '1.2rem',
    xxl: '2.4rem',
  },
  boxShadows: {
    '1': '0 0 4px 2px rgba(0, 0, 0, .2)',
    '2': '0 0 8px 2px rgba(0, 0, 0, .2)',
    '3': '2px 2px 4px 2px rgba(0, 0, 0, .2)',
    '4': '2px 2px 8px 0 rgba(0, 0, 0, .2)',
    '5': '4px 4px 4px 2px rgba(0, 0, 0, .2)',
  },
  breakpoints: {
    'xs-only': 'max-width: 599px',
    'sm-up': 'min-width: 600px',
    'md-up': 'min-width: 900px',
    'lg-up': 'min-width: 1200px',
    // 'xl-up': 'min-width: 1800px',
  },
  // clearfix: true,
  colors: {},
  colorGradients: true,
  cursors: [
    // General
    'auto',
    'default',
    'none',

    // Links & status
    'context-menu',
    'help',
    'pointer',
    'progress',
    'wait',

    // Selection
    'cell',
    'crosshair',
    'text',
    'vertical-text',

    // Drag & drop
    'alias',
    'copy',
    'move',
    'no-drop',
    'not-allowed',

    // Resize
    'all-scroll',
    'col-resize',
    'row-resize',
    'n-resize',
    'e-resize',
    's-resize',
    'w-resize',
    'ne-resize',
    'nw-resize',
    'se-resize',
    'sw-resize',
    'ew-resize',
    'ns-resize',
    'nesw-resize',
    'nwse-resize',

    // Zoom
    'zoom-in',
    'zoom-out',

    // Drag/drop
    'grab',
    'grabbing',
  ],
  customRules: {},
  disabledRules: [],
  display: {
    db: 'block',
    di: 'inline',
    dib: 'inline-block',
    df: 'flex',
    dfb: 'flex-block',
    dt: 'table',
    dtc: 'table-cell',
    dn: 'none',
  },
  flexDirection: {
    row: 'row',
    'row-reverse': 'row-reverse',
    col: 'column',
    'col-reverse': 'column-reverse',
    start: 'flex-start',
    end: 'flex-end',
  },
  flexOrder: {
    first: '-1',
    last: '1',
  },
  flexWrap: {
    wrap: 'wrap',
    reverse: 'reverse',
    none: 'nowrap',
  },
  floats: ['left', 'right', 'none'],
  fontFamilies: {
    system:
      '-apple-system, BlinkMacSystemFont, "avenir next", avenir, helvetica, "helvetica neue" ubuntu, roboto, noto, "segoe ui", arial, sans-serif',
    'sans-serif': 'helvetica, ariel, sans-serif',
    serif: 'georgia, times, serif',
    code: 'Consolas, monaco, monospace',

    athelas: 'athelas, georgia, serif',
    avenir: '"avenir next", avenir, sans-serif',
    baskerville: 'baskerville, serif',
    bodoni: '"Bodoni MT", serif',
    calisto: '"Calisto MT", serif',
    courier: '"Courier Next", courier, monospace',
    garamond: 'garamond, serif',
    georgia: 'georgia, serif',
    helvetica: '"helvetica neue", helvetica, sans-serif',
    times: 'times, serif',
  },
  fontSizes: {
    xxxl: '4em',
    xxl: '2.6em',
    xl: '1.9em',
    lg: '1.3em',
    md: '1em',
    sm: '0.85em',
    xs: '0.7em',
  },
  fontStyles: ['italic'],
  fontWeights: {
    bold: 'bold',
    normal: 'normal',
    '1': '100',
    '2': '200',
    '3': '300',
    '4': '400',
    '5': '500',
    '6': '600',
    '7': '700',
    '8': '800',
    '9': '900',
  },
  justifyContent: {
    start: 'flex-start',
    end: 'flex-end',
    center: 'center',
    between: 'space-between',
    around: 'space-around',
  },
  letterSpacing: {
    xxs: '-0.2em',
    xs: '-0.1em',
    sm: '-0.05em',
    md: 0,
    lg: '0.3em',
    xl: '0.6em',
    xxl: '1.2em',
  },
  lineHeights: {
    xxs: 0.5,
    xs: 0.75,
    sm: 1,
    md: 1.5,
    lg: 2,
    xl: 3,
    xxl: 4,
  },
  margins: {
    none: 0,
    auto: 'auto',
    xxs: '0.25rem',
    xs: '0.5rem',
    sm: '1rem',
    md: '2rem',
    lg: '4rem',
    xl: '8rem',
    xxl: '14rem',
  },
  opacity: {
    '100': 1.0,
    '90': 0.9,
    '80': 0.8,
    '70': 0.7,
    '60': 0.6,
    '50': 0.5,
    '40': 0.4,
    '30': 0.3,
    '20': 0.2,
    '10': 0.1,
    '05': 0.05,
    '025': 0.025,
    '0': 0,
  },
  overflow: ['visible', 'hidden', 'scroll', 'auto'],
  paddings: {
    none: 0,
    xxs: '0.25rem',
    xs: '0.5rem',
    sm: '1rem',
    md: '2rem',
    lg: '4rem',
    xl: '8rem',
    xxl: '14rem',
  },
  percentageSizes: {
    auto: 'auto',
    '0': '0%',
    '5': '5%',
    '10': '10%',
    '15': '15%',
    '20': '20%',
    '25': '25%',
    '30': '30%',
    '33': '33.3%',
    '40': '40%',
    '50': '50%',
    '60': '60%',
    '66': '66.6%',
    '70': '70%',
    '75': '75%',
    '80': '80%',
    '90': '90%',
    '100': '100%',
  },
  positions: ['relative', 'absolute', 'fixed'],
  positionValues: ['a', 'l', 't', 'r', 'b', 'x', 'y'],
  responsive: [
    'floats',
    'margin',
    'margin-percentages',
    'padding',
    'positions',
    'widths',
    'widths-max',
  ],
  spacing: {
    none: 0,
    auto: 'auto',
    xxs: '0.25rem',
    xs: '0.5rem',
    sm: '1rem',
    md: '2rem',
    lg: '4rem',
    xl: '8rem',
    xxl: '14rem',
  },
  spacingDirections: ['', 'l', 't', 'r', 'b', 'x', 'y'],
  textAlignment: ['left', 'right', 'center', 'justify'],
  textDecorations: {
    none: 'none',
    line: 'line-through',
    underline: 'underline',
  },
  textTransforms: {
    upper: 'uppercase',
    lower: 'lowercase',
    capital: 'capitalize',
  },
  verticalAlignment: {
    base: 'baseline',
    bot: 'bottom',
    top: 'top',
    'text-top': 'text-top',
    'text-bot': 'text-bottom',
  },
  visibility: { visible: 'visible', invisible: 'hidden' },
  whitespace: ['pre', 'nowrap', 'normal'],
  zIndex: [0, 100, 200, 300, 400, 500, 600, 700, 800, 900, 1000],
}

defaults.baseColors = {
  // Context colors
  primary: null,
  secondary: null,
  info: null,
  success: null,
  warning: null,
  danger: null,

  // Grayscale
  gray: '#7a7a7a',

  // General colors
  blue: '#3187c4',
  cyan: '#31c4a9',
  green: '#7db735',
  orange: '#dd6618',
  purple: '#963ebc',
  pink: '#bc328c',
  red: '#d8401e',
  yellow: '#efef00',
}

defaults.baseColors.primary = defaults.baseColors.cyan
defaults.baseColors.secondary = defaults.baseColors.gray
defaults.baseColors.info = defaults.baseColors.blue
defaults.baseColors.success = defaults.baseColors.green
defaults.baseColors.warning = defaults.baseColors.orange
defaults.baseColors.danger = defaults.baseColors.red

export default defaults
